### PR TITLE
Fix content fetcher bug

### LINKED ISSUE #830: Content fetcher gets latest version based on release date, not version number
**Description**
Content fetcher fetch version 1.24 as newest version, because the newest tag on kyma is patch release for 1.24.
Current tag list on kyma :
- 1.24.11 (Feb 17)
- 1.24.10 (Feb 11) 
- 2.04 (Jan 26)

**Expected result**
Content fetcher sort by version not by tag release date

**Actual result**

Content fetcher sort by tag release date

**Steps to reproduce**
Run Content fetcher
**Troubleshooting**

### PR DESCRIPTION
**Pull request by Lyczeq**
**Description**
Fix content fetcher bug
Changes proposed in this pull request:

- Update Readme file to facilitate the development
- Change version comparison
- Remove needless files

**Related issue(s)**
Fixes #830

### CODE REVIEW

File: tools/content-loader/src/prepare-docs/release-fetcher.ts [hunk 1]
```diff
@@ -74,18 +74,21 @@ export class ReleaseFetcher {
...
-        .sort((first, second) => {
-          const firstDate = new Date(first.published_at);
-          const secondDate = new Date(second.published_at);
-          return firstDate.getTime() - secondDate.getTime();
-        })
-        .reverse();
+      const sorted = value.sort((first, second) => {
+        const firstTag = first.tag_name;
+        const secondTag = second.tag_name;
+        return Number.parseFloat(secondTag) - Number.parseFloat(firstTag);
```
Comment (qbalukom) [inline tools/content-loader/src/prepare-docs/release-fetcher.ts:80]: I don't think this will sort correctly. as version `1.9.0` will be treated as `1.9`, but version `1.10.0` will be treated as `1.1`.
Also it won't distinguish between `1.10.0` and `1.10.1` (as everything after and including the second period will be ignored), not to mention `1.10.0-rc1` vs. `1.10.0-rc2`

Comment (qbalukom) [reply tools/content-loader/src/prepare-docs/release-fetcher.ts:80]: there are tools for proper handling of semantic versioning, such as https://github.com/npm/node-semver

**Review by qbalukom — CHANGES_REQUESTED** [review]

File: README.md [hunk 2]
```diff
@@ -34,6 +36,22 @@ Launch the development server with the hot reloading functionality that allows a
 npm run develop
 ```
 
+To fetch `docs` from the `Kyma` repository, go to the `scripts/prepare-content.sh` file and change  `APP_DOCS_OUTPUT` to:
+```
+APP_DOCS_OUTPUT="{FULL_PATH_TO_REPOSITORY}/content/docs"
+```
+Then go to the root directory of the repostory and run the following command:
```
Comment (grego952) [inline README.md:43]:
```suggestion
Then go to the root directory of the repository and run the following command:
```

File: README.md [hunk 3]
```diff
@@ -34,6 +36,22 @@ Launch the development server with the hot reloading functionality that allows a
 npm run develop
 ```
 
+To fetch `docs` from the `Kyma` repository, go to the `scripts/prepare-content.sh` file and change  `APP_DOCS_OUTPUT` to:
```
Comment (grego952) [inline README.md:39]:
```suggestion
To fetch `docs` from the `Kyma` repository, go to the `scripts/prepare-content.sh` file and change `APP_DOCS_OUTPUT` to:
```

Comment (grego952) [inline README.md:39]:
```suggestion
To fetch `docs` from the `Kyma` repository, go to the `scripts/prepare-content.sh` file and change `APP_DOCS_OUTPUT` to:
```

File: README.md (hunk 2 above)
Comment (grego952) [inline README.md:43]:
```suggestion
Then go to the root directory of the repository and run the following command:
```

**Review by grego952 — DISMISSED** [review]

File: tools/content-loader/src/prepare-docs/release-fetcher.ts [hunk 4]
```diff
@@ -74,18 +74,20 @@ export class ReleaseFetcher {
...
+        const firstTag = first.tag_name;
+        const secondTag = second.tag_name;
+        return semverGt(secondTag, firstTag) ? 1 : -1;
+      });
 
       result.set(key, sorted[0]);
     });
-
-    return result;
+    const sortedResult = new Map(
```
Comment (qbalukom) [inline tools/content-loader/src/prepare-docs/release-fetcher.ts:85]: `return new Map(`?
no need to assign to a new variable

File: tools/content-loader/src/prepare-docs/release-fetcher.ts [hunk 5]
```diff
@@ -74,18 +74,20 @@ export class ReleaseFetcher {
...
-          return firstDate.getTime() - secondDate.getTime();
-        })
-        .reverse();
+      const sorted = value.sort((first, second) => {
+        const firstTag = first.tag_name;
+        const secondTag = second.tag_name;
+        return semverGt(secondTag, firstTag) ? 1 : -1;
+      });
 
       result.set(key, sorted[0]);
```
Comment (qbalukom) [inline tools/content-loader/src/prepare-docs/release-fetcher.ts:83]: i won't lie, i would love to see it done as `groupedReleases.reduce` instead of modifying a variable external to the loop... but it's not part of your changes and not a blocker :)
just if you feel like experimenting :)

**Review by qbalukom — CHANGES_REQUESTED** [review]

**Review by qbalukom — APPROVED** [review]

**Review by grego952 — APPROVED** [review]
